version: "3.7"
services:
<<<<<<< HEAD
  postgresql_db:
    container_name: "postgres"
    image: "postgres"
    environment:
      PGDATA: data/data_postgress
      POSTGRES_USER: tuantrancode
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_db:/data/postgress
    ports:
      - "5332:5432"
    networks:
      postgresql_db:
    restart: unless-stopped
=======

  postgresql_db:
    container_name: "postgres"
    image: "postgres"
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: /data/postgress
      POSTGRES_USER: tuantrancode
      POSTGRES_PASSWORD: tuantrancode
    volumes:
      - postgresql_db:/data/postgress
    networks:
      postgresql_db:
>>>>>>> origin/main
networks:
  postgresql_db:
    driver: bridge
volumes:
  postgresql_db:
