version: "3.7"
services:
  postgresql_db:
    container_name: "postgres"
    image: "postgres"
    environment:
      PGDATA: data/data_postgress
      POSTGRES_USER: tuantrancode
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_db:/data/postgress
    ports:
      - "5332:5432"
    networks:
      postgresql_db:
    restart: unless-stopped
networks:
  postgresql_db:
    driver: bridge
volumes:
  postgresql_db:
